PRAGMA foreign_keys=ON;

SELECT * FROM SHARING WHERE book = 1;
SELECT * FROM BOOKITEM WHERE id = 1; 

INSERT INTO SHARING VALUES ('2018/07/01', '2018/07/15', 1, 3, 1);

SELECT * FROM SHARING WHERE book = 1;
SELECT * FROM BOOKITEM WHERE id = 1; 
